'use client';
import { ArrowUpRight, Download } from 'lucide-react';
import { disclaimer, type Source } from '@/lib/territory';
export function EvidencePanel({ sources, focus }: { sources: Source[]; focus: string | null }) {
  const ordered = focus ? [...sources.filter(s => s.ID === focus), ...sources.filter(s => s.ID !== focus)] : sources;
  return <><div className="notice"><b>Origen oficial · preparación derivada</b><p>Selección, reproyección, recorte y simplificación para visualización. El área preparada ofrece cobertura parcial de laguna y zona marina.</p></div>
    <div className="evidence-downloads"><a href="/data/preparation.json" download className="text-link"><Download size={15} /> Registro de preparación</a><a href="/data/metadata-evidence.zip" download className="text-link"><Download size={15} /> Metadatos y condiciones</a></div>
    {ordered.map(s => <article className="source-card" key={s.ID} id={`source-${s.ID}`}><div className="source-top"><span className="source-code">{s.ID}</span><span className="badge official" title="Dato publicado por una institución pública">OFICIAL</span><small>{s.Institución}</small></div><h3>{s.Nombre}</h3><dl><dt>Fecha del dato</dt><dd>{s.Fecha}</dd><dt>Tipo / formato</dt><dd>{s.Tipo} · {s.Formato}</dd><dt>Cobertura original</dt><dd>{s.Cobertura}</dd><dt>Escala / resolución</dt><dd>{s.Resolución}</dd><dt>Consulta</dt><dd>{s.Consulta}</dd><dt>Reutilización</dt><dd>{s.Licencia}</dd></dl><p className="source-limitation">{s.Limitaciones}</p><a className="text-link" href={s.URL} target="_blank" rel="noreferrer">Consultar fuente original <ArrowUpRight size={16} /></a></article>)}
    <article className="source-card"><div className="source-top"><span className="source-code">S50</span><span className="badge official">CONTEXTO OFICIAL</span></div><h3>Áreas geoestadísticas estatales</h3><p>INEGI · Marco Geoestadístico, diciembre de 2025. Campeche, Quintana Roo y Yucatán. GeoJSON EPSG:6365 preparado para el fondo regional. Consulta: 3 de septiembre de 2026.</p><p className="source-limitation">Contexto de navegación, separado de los cuatro datasets del núcleo. No define límites jurídicos ni sustituye la costa S01. Simplificación de 20 m; precisión local no certificada. Libre uso INEGI con atribución y declaración de transformaciones.</p><a className="text-link" href="https://www.inegi.org.mx/servicios/catalogounico.html" target="_blank" rel="noreferrer">Documentación del servicio <ArrowUpRight size={16} /></a></article>
    <a className="text-link" href="/data/research-catalogue.json" download><Download size={15} /> Catálogo de investigación de Etapa A</a></>;
}
export function AboutPanel() {
  return <><p className="body-large">La información del litoral existe. Leerla en conjunto permite hacer mejores preguntas.</p><p>EVEN desarrolla este prototipo de integración territorial para el Colectivo por la Costa. Reúne datos públicos del corredor Yucalpetén–Chelem–Chuburná y hace visibles sus fuentes, fechas y límites.</p><div className="notice"><span className="badge preliminary" title="Interpretación sujeta a revisión por especialistas del Colectivo por la Costa">PRELIMINAR</span><p>{disclaimer}</p></div><p>El encuadre del mapa es operativo. No representa un límite científico ni garantiza cobertura completa de la laguna o de la zona marina. La ventana de auditoría original y el área preparada para esta visualización son ámbitos distintos.</p><p>Los especialistas deben validar la delimitación de celda y subceldas y las interpretaciones físicas. La representación de los datos oficiales aquí reunidos no equivale a esa validación.</p><h3>Leer los estados de la información</h3><dl className="status-explainer"><dt>OFICIAL</dt><dd>Origen publicado por una institución pública.</dd><dt>DERIVADO</dt><dd>Información preparada a partir de fuentes oficiales; no publicada directamente por la institución en esta forma.</dd><dt>PRELIMINAR</dt><dd>Ámbito o interpretación sujeto a revisión científica.</dd></dl><p className="fine-print">La cartografía requiere WebGL. También puedes consultar fuentes y fichas de localidades desde el menú, sin seleccionar elementos en el mapa.</p></>;
}
