import { allVisible, type Visibility } from './territory';
export type Chapter = { title: string; text: string; note: string; visibility: Visibility; place?: string; evidence?: boolean };
const coast: Visibility = { coast: true, localities: false, mangrove: false, wetlands: false, water: false };
export const chapters: Chapter[] = [
  { title: 'La costa es un sistema.', text: 'El litoral conecta territorios. Observar juntos la costa, los ecosistemas y las localidades ayuda a formular preguntas sobre esas relaciones.', note: 'El encuadre es un área preliminar de estudio. Las relaciones físicas deben ser validadas por especialistas.', visibility: allVisible },
  { title: 'El litoral cambia.', text: 'Aquí vemos una costa de referencia de INEGI. Un solo conjunto cartográfico no permite medir cuánto ni cómo ha cambiado la playa.', note: 'No se localizó una serie de líneas de costa local, homogénea y validada para este MVP. La comparación histórica queda pendiente.', visibility: coast },
  { title: 'Infraestructura: una lectura pendiente.', text: 'Los puertos y las obras costeras requieren información sobre geometría, función y fecha. Incorporarlos es una ampliación condicionada de este prototipo.', note: 'No se dibujan estructuras aproximadas ni se atribuyen efectos sobre la costa. Su interpretación espera revisión científica.', visibility: { ...coast, localities: true } },
  { title: 'Ecosistemas, con fecha.', text: 'Manglar, otros humedales y cuerpos de agua forman tres lecturas distintas de la cartografía CONABIO de 2020.', note: 'La escala es 1:50,000. La ausencia de un polígono no demuestra ausencia ecológica actual; no es una evaluación predial.', visibility: { ...allVisible, localities: false } },
  { title: 'Territorio habitado.', text: 'Chelem, Chuburná y Progreso sitúan la exploración. Sus polígonos son unidades geoestadísticas y su población corresponde al Censo de 2020.', note: 'Selecciona una localidad para consultar su ficha. No hay padrón catastral ni diagnóstico de propiedades.', visibility: { ...coast, localities: true }, place: 'S02-310590003' },
  { title: 'La información existe.', text: 'Pero está fragmentada. Cuatro datasets oficiales permiten representar cinco temas, con fechas, escalas y condiciones distintas.', note: 'Cada elemento conserva su fuente y su identificador. Las transformaciones de visualización están documentadas.', visibility: allVisible, evidence: true },
  { title: 'Una sola lectura del territorio.', text: 'Ciencia, territorio e información pública en un mismo espacio. Una base para conversar, contrastar fuentes y decidir qué investigar después.', note: 'Los límites de celda y subceldas y cualquier interpretación de dinámica litoral siguen sujetos a validación científica.', visibility: allVisible },
];
export const openingLines = ['La costa no funciona predio por predio.', 'El litoral conecta diferentes territorios.', 'Lo que ocurre en un punto puede relacionarse con otros.', 'Para comprenderlo necesitamos observar el sistema completo.'];
