import { allVisible, type Visibility } from './territory';
export type Chapter = { title: string; text: string; note: string; visibility: Visibility; place?: string; evidence?: boolean };
const coast: Visibility = { coast: true, localities: false, mangrove: false, wetlands: false, water: false };
export const chapters: Chapter[] = [
  { title: 'La costa es un sistema.', text: 'Costa, ecosistemas y localidades. Observarlos juntos ayuda a preguntar cómo se relacionan.', note: 'El encuadre es un área preliminar de estudio. Las relaciones físicas deben ser validadas por especialistas.', visibility: allVisible },
  { title: 'El litoral cambia.', text: 'Esta es una costa de referencia de INEGI. Una sola fecha no permite medir el cambio de la playa.', note: 'No se localizó una serie de líneas de costa local, homogénea y validada para este MVP. La comparación histórica queda pendiente.', visibility: coast },
  { title: 'Infraestructura: una lectura pendiente.', text: 'Leer los puertos y las obras exige conocer su forma, función y fecha. Su integración está condicionada a esa evidencia.', note: 'No se dibujan estructuras aproximadas ni se atribuyen efectos sobre la costa. Su interpretación espera revisión científica.', visibility: { ...coast, localities: true } },
  { title: 'Ecosistemas, con fecha.', text: 'Manglar, otros humedales y cuerpos de agua: tres lecturas distintas de CONABIO, con fecha de 2020.', note: 'La escala es 1:50,000. La ausencia de un polígono no demuestra ausencia ecológica actual; no es una evaluación predial.', visibility: { ...allVisible, localities: false } },
  { title: 'Territorio habitado.', text: 'Chelem, Chuburná y Progreso. Polígonos geoestadísticos y población del Censo de 2020 para situar la exploración.', note: 'Selecciona una localidad para consultar su ficha. No hay padrón catastral ni diagnóstico de propiedades.', visibility: { ...coast, localities: true }, place: 'S02-310590003' },
  { title: 'La información existe.', text: 'Cuatro conjuntos oficiales, cinco temas. Cada uno tiene fechas, escalas y condiciones distintas.', note: 'Cada elemento conserva su fuente y su identificador. Las transformaciones de visualización están documentadas.', visibility: allVisible, evidence: true },
  { title: 'Una sola lectura del territorio.', text: 'Una base común para conversar, contrastar fuentes y decidir qué investigar. Ahora puedes explorar el territorio a tu ritmo.', note: 'Los límites de celda y subceldas y cualquier interpretación de dinámica litoral siguen sujetos a validación científica.', visibility: allVisible },
];
